apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/k8srequiredresources.yaml
  - templates/k8sdisallowprivileged.yaml
  - templates/k8srequiredlabels.yaml
  - constraints/require-workload-resources.yaml
  - constraints/disallow-privileged-dev.yaml
  - constraints/require-namespace-labels.yaml
